/** Persistent project defaults, hard limits, and instrument defaults. */
export const PROJECT_CONSTANTS = Object.freeze({
  defaultProjectTitle: "Pianola Project",
  ppqn: 960,
  schemaVersion: 2,
  defaultMeasureCount: 4,
  defaultTempoBpm: 120,
  minimumTempoBpm: 30,
  maximumTempoBpm: 240,
  tempoStepBpm: 0.1,
  defaultTimeSignatureNumerator: 4,
  defaultTimeSignatureDenominator: 4,
  minimumTimeSignatureNumerator: 1,
  maximumTimeSignatureNumerator: 32,
  minimumMeasureCount: 1,
  maximumMeasureCount: 256,
  defaultMasterGain: 0.72,
  defaultMasterMuted: false,
  defaultMasterTuningFrequencyHz: 440,
  minimumMasterTuningFrequencyHz: 400,
  maximumMasterTuningFrequencyHz: 480,
  masterTuningStepHz: 0.1,
  minimumMasterGain: 0,
  maximumMasterGain: 1,
  defaultSynthPolyphony: 1,
  minimumSynthPolyphony: 1,
  maximumSynthPolyphony: 16,
  maximumEntityIdLength: 160,
  maximumProjectTitleLength: 200,
  // Clip limits protect Pianola project parsing and inspector usability.
  maximumClipNameLength: 128,
  maximumSectionCommentLength: 1_000,
  maximumClipCount: 256,
  maximumClipGroupCount: 256,
  maximumClipGroupDepth: 16,
  maximumInstrumentNameLength: 128,
  maximumInstrumentCount: 256,
  // This rendering and validation budget is applied independently per clip.
  maximumNoteCount: 250_000,
  maximumInstrumentDescriptorCount: 128,
  maximumDescriptorParameterCount: 256,
  maximumHistoryEntries: 200,
  defaultLoopEnabled: false,
  defaultAutoAdvanceEnabled: true,
  defaultAutoScrollEnabled: false,
  defaultClipBypassEnabled: false,
  defaultClipGroupBypassEnabled: false,
  defaultInstrumentMuted: false,
  defaultClipColor: "#171a20",
  defaultClipGroupColor: "#79a7ff",
  defaultInstrumentSolo: false,
  defaultInstrumentGain: 0.82,
  minimumMidiPitch: 0,
  maximumMidiPitch: 127,
  minimumMidiVelocity: 0,
  maximumMidiVelocity: 127,
} as const);
