/** Persistent project defaults, hard limits, and instrument defaults. */
export const PROJECT_CONSTANTS = Object.freeze({
  ppqn: 960,
  schemaVersion: 3,
  defaultMeasureCount: 16,
  defaultTempoBpm: 120,
  minimumTempoBpm: 30,
  maximumTempoBpm: 240,
  tempoStepBpm: 0.1,
  defaultTimeSignatureNumerator: 4,
  defaultTimeSignatureDenominator: 4,
  minimumTimeSignatureNumerator: 1,
  maximumTimeSignatureNumerator: 32,
  minimumMeasureCount: 1,
  maximumMeasureCount: 256,
  defaultMasterGain: 0.72,
  defaultMasterMuted: false,
  defaultMasterTuningFrequencyHz: 440,
  minimumMasterTuningFrequencyHz: 400,
  maximumMasterTuningFrequencyHz: 480,
  masterTuningStepHz: 0.1,
  minimumMasterGain: 0,
  maximumMasterGain: 1,
  defaultSubtractiveSynthPolyphony: 1,
  minimumSubtractiveSynthPolyphony: 1,
  maximumSubtractiveSynthPolyphony: 16,
  maximumEntityIdLength: 160,
  maximumProjectTitleLength: 200,
  // Clip limits protect native-file parsing and inspector usability.
  maximumClipNameLength: 128,
  maximumClipCount: 256,
  maximumInstrumentNameLength: 128,
  maximumInstrumentCount: 256,
  // This rendering and validation budget is applied independently per clip.
  maximumNoteCount: 250_000,
  maximumInstrumentDescriptorCount: 128,
  maximumDescriptorParameterCount: 256,
  maximumHistoryEntries: 200,
  defaultLoopEnabled: false,
  defaultAutoAdvanceEnabled: true,
  defaultInstrumentMuted: false,
  defaultClipInstrumentLocked: false,
  defaultInstrumentSolo: false,
  defaultInstrumentGain: 0.82,
  minimumMidiPitch: 0,
  maximumMidiPitch: 127,
  minimumMidiVelocity: 0,
  maximumMidiVelocity: 127,
} as const);
export const INSTRUMENT_CONSTANTS = Object.freeze({
  minimumGain: 0,
  maximumGain: 1,
  pan: 0,
  defaultOscillatorWaveform: "sawtooth",
  oscillatorWaveformOptions: Object.freeze([
    Object.freeze({
      value: "sine",
      label: "Sine",
    }),
    Object.freeze({
      value: "triangle",
      label: "Triangle",
    }),
    Object.freeze({
      value: "sawtooth",
      label: "Saw",
    }),
    Object.freeze({
      value: "square",
      label: "Square",
    }),
  ] as const),
  oscillatorDetuneCents: 0,
  pulseWidth: 0.5,
  minimumPulseWidth: 0.05,
  maximumPulseWidth: 0.95,
  attackSeconds: 0.012,
  decaySeconds: 0.18,
  sustainLevel: 0.72,
  releaseSeconds: 0.42,
  filterCutoffHz: 8_000,
  minimumFilterCutoffHz: 20,
  maximumFilterCutoffHz: 20_000,
  filterResonance: 0.2,
  minimumFilterResonance: 0,
  maximumFilterResonance: 24,
  filterEnvelopeAmountOctaves: 1,
  minimumFilterEnvelopeAmountOctaves: 0,
  maximumFilterEnvelopeAmountOctaves: 8,
  filterAttackSeconds: 0.008,
  filterDecaySeconds: 0.32,
  filterSustainLevel: 0.28,
  filterReleaseSeconds: 0.36,
  maximumEnvelopeTimeSeconds: 2,
  maximumEnvelopeDecaySeconds: 10,
  transposeSemitones: 0,
  timingOffsetTicks: 0,
  gateRatio: 1,
  velocityScale: 1,
  probability: 1,
} as const);
