/** Touch, pointer, keyboard-preview, and pinch gesture tuning. */
export const INTERACTION_CONSTANTS = Object.freeze({
  longPressDelayMs: 300,
  penLongPressDelayMs: 280,
  longPressMovementToleranceCssPixels: 12,
  pianoKeyLongPressDelayMs: 520,
  pianoKeyPenLongPressDelayMs: 280,
  pianoKeyLongPressMovementToleranceCssPixels: 10,
  instrumentNameLongPressDelayMs: 520,
  instrumentNameLongPressMovementToleranceCssPixels: 10,
  touchDoubleTapDelayMs: 360,
  touchDoubleTapDistanceCssPixels: 24,
  tapMovementToleranceCssPixels: 10,
  twoFingerTapMaximumDurationMs: 280,
  twoFingerTapMovementToleranceCssPixels: 10,
  twoFingerDoubleTapDelayMs: 360,
  twoFingerDoubleTapDistanceCssPixels: 32,
  mouseResizeHandleCssPixels: 8,
  touchResizeHandleCssPixels: 16,
  mouseNoteHitEnvelopeCssPixels: 2,
  touchNoteHitEnvelopeCssPixels: 10,
  minimumPinchDistanceCssPixels: 8,
  pinchAxisLockRatio: 1.35,
  minimumPinchScale: 0.82,
  maximumPinchScale: 1.22,
  pinchScaleDeadZone: 0.003,
} as const);
