/** Tonal pitch-snap vocabulary and defaults. */
export const TONAL_SNAP_CONSTANTS = Object.freeze({
  defaultEnabled: false,
  defaultVisualGuideEnabled: false,
  defaultTonicPitchClass: 0,
  defaultPatternId: "ionian",
  defaultScaleDegreeIndex: null,
  scaleDegreeRomanNumerals: Object.freeze([
    "I",
    "II",
    "III",
    "IV",
    "V",
    "VI",
    "VII",
  ] as const),
  // Labels are neutral fallbacks; the UI derives the preferred enharmonic
  // spelling from the selected pattern and its total accidental cost.
  tonicOptions: Object.freeze([
    Object.freeze({ value: 0, label: "C" }),
    Object.freeze({ value: 1, label: "C#" }),
    Object.freeze({ value: 2, label: "D" }),
    Object.freeze({ value: 3, label: "D#" }),
    Object.freeze({ value: 4, label: "E" }),
    Object.freeze({ value: 5, label: "F" }),
    Object.freeze({ value: 6, label: "F#" }),
    Object.freeze({ value: 7, label: "G" }),
    Object.freeze({ value: 8, label: "G#" }),
    Object.freeze({ value: 9, label: "A" }),
    Object.freeze({ value: 10, label: "A#" }),
    Object.freeze({ value: 11, label: "B" }),
  ] as const),
  patternFamilies: Object.freeze([
    Object.freeze({
      id: "diatonic",
      label: "Diatonic modes",
    }),
    Object.freeze({
      id: "minor-altered",
      label: "Minor and altered",
    }),
    Object.freeze({
      id: "pentatonic-folk",
      label: "Pentatonic and folk",
    }),
    Object.freeze({
      id: "symmetric",
      label: "Symmetric scales",
    }),
  ] as const),
  patterns: Object.freeze([
    Object.freeze({
      id: "ionian",
      label: "Ionian",
      family: "diatonic",
      intervals: Object.freeze([0, 2, 4, 5, 7, 9, 11]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "dorian",
      label: "Dorian",
      family: "diatonic",
      intervals: Object.freeze([0, 2, 3, 5, 7, 9, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "phrygian",
      label: "Phrygian",
      family: "diatonic",
      intervals: Object.freeze([0, 1, 3, 5, 7, 8, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "lydian",
      label: "Lydian",
      family: "diatonic",
      intervals: Object.freeze([0, 2, 4, 6, 7, 9, 11]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "mixolydian",
      label: "Mixolydian",
      family: "diatonic",
      intervals: Object.freeze([0, 2, 4, 5, 7, 9, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "aeolian",
      label: "Aeolian",
      family: "diatonic",
      intervals: Object.freeze([0, 2, 3, 5, 7, 8, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "locrian",
      label: "Locrian",
      family: "diatonic",
      intervals: Object.freeze([0, 1, 3, 5, 6, 8, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "harmonic-minor",
      label: "Harmonic minor",
      family: "minor-altered",
      intervals: Object.freeze([0, 2, 3, 5, 7, 8, 11]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "melodic-minor",
      label: "Melodic minor (ascending)",
      family: "minor-altered",
      intervals: Object.freeze([0, 2, 3, 5, 7, 9, 11]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "phrygian-dominant",
      label: "Phrygian dominant",
      family: "minor-altered",
      intervals: Object.freeze([0, 1, 4, 5, 7, 8, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "double-harmonic-major",
      label: "Double harmonic major",
      family: "minor-altered",
      intervals: Object.freeze([0, 1, 4, 5, 7, 8, 11]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "hungarian-minor",
      label: "Hungarian minor",
      family: "minor-altered",
      intervals: Object.freeze([0, 2, 3, 6, 7, 8, 11]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 6]),
    }),
    Object.freeze({
      id: "major-pentatonic",
      label: "Major pentatonic",
      family: "pentatonic-folk",
      intervals: Object.freeze([0, 2, 4, 7, 9]),
      letterOffsets: Object.freeze([0, 1, 2, 4, 5]),
    }),
    Object.freeze({
      id: "minor-pentatonic",
      label: "Minor pentatonic",
      family: "pentatonic-folk",
      intervals: Object.freeze([0, 3, 5, 7, 10]),
      letterOffsets: Object.freeze([0, 2, 3, 4, 6]),
    }),
    Object.freeze({
      id: "blues",
      label: "Blues",
      family: "pentatonic-folk",
      intervals: Object.freeze([0, 3, 5, 6, 7, 10]),
      letterOffsets: Object.freeze([0, 2, 3, 3, 4, 6]),
    }),
    Object.freeze({
      id: "hirajoshi",
      label: "Hirajoshi",
      family: "pentatonic-folk",
      intervals: Object.freeze([0, 2, 3, 7, 8]),
      letterOffsets: Object.freeze([0, 1, 2, 4, 5]),
    }),
    Object.freeze({
      id: "in-sen",
      label: "In Sen",
      family: "pentatonic-folk",
      intervals: Object.freeze([0, 1, 5, 7, 10]),
      letterOffsets: Object.freeze([0, 1, 3, 4, 6]),
    }),
    Object.freeze({
      id: "whole-tone",
      label: "Whole tone",
      family: "symmetric",
      intervals: Object.freeze([0, 2, 4, 6, 8, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5]),
    }),
    Object.freeze({
      id: "diminished-whole-half",
      label: "Diminished (whole-half)",
      family: "symmetric",
      intervals: Object.freeze([0, 2, 3, 5, 6, 8, 9, 11]),
      letterOffsets: Object.freeze([0, 1, 2, 3, 4, 5, 5, 6]),
    }),
    Object.freeze({
      id: "diminished-half-whole",
      label: "Diminished (half-whole)",
      family: "symmetric",
      intervals: Object.freeze([0, 1, 3, 4, 6, 7, 9, 10]),
      letterOffsets: Object.freeze([0, 1, 2, 2, 3, 4, 5, 6]),
    }),
  ] as const),
} as const);
