/** Persistent instrument defaults and validation limits. */
export const INSTRUMENT_CONSTANTS = Object.freeze({
  minimumGain: 0,
  maximumGain: 1,
  pan: 0,
  defaultOscillatorWaveform: "sawtooth",
  oscillatorWaveformOptions: Object.freeze([
    Object.freeze({ value: "sine", label: "Sine" }),
    Object.freeze({ value: "triangle", label: "Triangle" }),
    Object.freeze({ value: "sawtooth", label: "Saw" }),
    Object.freeze({ value: "square", label: "Square" }),
  ] as const),
  oscillatorDetuneCents: 0,
  oscillatorFreePhase: false,
  pulseWidth: 0.5,
  minimumPulseWidth: 0.05,
  maximumPulseWidth: 0.95,
  attackSeconds: 0.012,
  decaySeconds: 0.18,
  sustainLevel: 0.72,
  releaseSeconds: 0.42,
  filterCutoffHz: 8_000,
  minimumFilterCutoffHz: 20,
  maximumFilterCutoffHz: 20_000,
  filterResonance: 0.2,
  minimumFilterResonance: 0,
  maximumFilterResonance: 24,
  filterKeyTracking: 0,
  minimumFilterKeyTracking: 0,
  maximumFilterKeyTracking: 1,
  filterEnvelopeAmountOctaves: 1,
  minimumFilterEnvelopeAmountOctaves: 0,
  maximumFilterEnvelopeAmountOctaves: 8,
  filterAttackSeconds: 0.008,
  filterDecaySeconds: 0.32,
  filterSustainLevel: 0.28,
  filterReleaseSeconds: 0.36,
  envelopeCurve: 0.35,
  legacyEnvelopeCurve: 0,
  minimumEnvelopeCurve: -1,
  maximumEnvelopeCurve: 1,
  maximumEnvelopeTimeSeconds: 2,
  maximumEnvelopeDecaySeconds: 10,
  transposeSemitones: 0,
  timingOffsetTicks: 0,
  gateRatio: 1,
  velocityScale: 1,
  probability: 1,
} as const);
